---
title: "MySqlDb_v1"
author: "Philip Tanofsky"
date: "1/15/2022"
output: html_document
---




```{r message=FALSE, warning=FALSE}
library(RMariaDB)

localuserpassword <- "BostonCeltics17"
# The connection method below uses a password stored in a variable.
# To use this set localuserpassword="The password of newspaper_search_results_user"

nbaDb <- dbConnect(MariaDB(), user='nba_game_statistics_user', password=localuserpassword, dbname='nba_game_statistics', host='localhost')

dbListTables(nbaDb)

# Create the query statement.
query <- "INSERT INTO schedule (
GAME_ID,
DATE,
HOME_TEAM,
AWAY_TEAM,
HOME_TEAM_SCORE,
AWAY_TEAM_SCORE)
VALUES('1000001',
'2021-10-01',
'BOS',
'PHI',
'101',
'99');"

# Optional. Prints out the query in case you need to troubleshoot it.
print(query)

# Execute the query on the storiesDb that we connected to above.
rsInsert <- dbSendQuery(nbaDb, query)

# Clear the result.
dbClearResult(rsInsert)

# Disconnect to clean up the connection to the database.

dbDisconnect(nbaDb)
```

```{r message=FALSE, warning=FALSE}
dbDisconnect(nbaDb)
```

```{r message=FALSE, warning=FALSE}

```

```{r message=FALSE, warning=FALSE}

```

```{r message=FALSE, warning=FALSE}

```

```{r message=FALSE, warning=FALSE}

```

```{r message=FALSE, warning=FALSE}

```
